### ISSUE TITLE
Set text color to white with a black stroke

### ISSUE THREAD

**Issue by montanaflynn** [montanaflynn/meme-generator#1]
Using `SetRGB(255, 255, 255)` [here](https://github.com/montanaflynn/meme-generator/blob/master/main.go#L43) didn't set the color to white as expected. 

Likewise I wasn't able to create a stroke on the text in any color using [this method](https://godoc.org/github.com/fogleman/gg#Context.Stroke).

**Comment by flopp** [comment]
I think you're using the wrong function.

`SetRGB(r,g,b float64)` takes 3 floats (range 0 ... 1.0) as parameters.

You probably want to use

`SetRGB255(r,g,b int)`

**Comment by montanaflynn** [comment]
That was definitely the problem, I just checked and it works beautifully, thanks a lot!

Is there a way to put a black stroke on the now white text?

**Comment by flopp** [comment]
Oh, I don't know.

**Comment by fogleman** [comment]
@montanaflynn I've written a meme generator myself, and the approach I've always taken is to render the text multiple times with an offset to produce the border. See here:

https://github.com/fogleman/pyMeme/blob/master/core.py#L134-L141

So you'd set the color to black, draw with offsets, set color to white, draw with zero offset.

**Comment by montanaflynn** [comment]
Thanks for the suggestion @fogleman, I attempted to first draw a black text and then put white text over it with limited success (it works good for the letters in the middle but not for the outer letters)

I did see that freetype has stroke functionality here:  https://github.com/golang/freetype/blob/master/raster/stroke.go 

Is that not capable of adding a black stroke to the text?

**Comment by fogleman** [comment]
Nah. The code that turns glyphs into paths would have to create the strokes somehow. Even then, it probably wouldn't look like you want. (Been there, done that. You'd want the stroke to be completely outside the glyph. But normally, strokes are rendered along the center of the path.)

I tweaked the text.go example to do what I described before and it works well:

http://i.imgur.com/fNoxzjS.png

https://gist.github.com/fogleman/9cff4addf4d452f8657d

**Comment by montanaflynn** [comment]
Wow that's great, thanks for sharing your experience and knowledge! I'd be lying if I said I understood what was going on in the code but it does the job perfectly. You've already done enough but would you mind explaining the logic that is happening in these lines? I understand what's technically happening, just not sure how why it works or how you got there. 

``` go
    for dy := -strokeSize; dy <= strokeSize; dy++ {
        for dx := -strokeSize; dx <= strokeSize; dx++ {
            // give it rounded corners
            if dx*dx+dy*dy >= strokeSize*strokeSize {
                continue
            }
```

**Comment by montanaflynn** [comment]
![I'll close this since both issues have been resolved by @flopp and @fogleman.](https://cloud.githubusercontent.com/assets/24260/13276769/7811b96a-da77-11e5-843d-12508a32d5b8.png)
